### ISSUE TITLE
windows.devices.geolocation installation fails in electronjs

### ISSUE THREAD

**Issue by appskitchen** [NodeRT/NodeRT#106]
Hi,
 I've windows 10, visual studio 2017, nodejs 10.8.0. I'm trying to install '@nodert-win10/windows.devices.geolocation' module in an electronjs app(I've node-gyp too), but it fails. Here are the error details  - 
PS C:\Users\mmusa\Desktop\Dev\myApp> npm i npm install @nodert-win10/windows.devices.geolocation

> @nodert-win10/windows.devices.geolocation@0.2.96 install C:\Users\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation
> node-gyp rebuild --msvs_version=2015

```
C:\Users\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
..\_nodert_generated.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\
Users\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation\build\binding.vcxproj]
..\CollectionsConverterUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment varia
ble [C:\Users\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation\build\binding.vcxproj]
..\NodeRtUtils.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\Users\
mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation\build\binding.vcxproj]
..\OpaqueWrapper.cpp : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search path using /AI or by setting the LIBPATH environment variable [C:\User
s\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation\build\binding.vcxproj]
  win_delay_load_hook.cc
C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_load_hook.cc : fatal error C1107: could not find assembly 'Windows.winmd': please specify the assembly search p
ath using /AI or by setting the LIBPATH environment variable [C:\Users\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:238:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd C:\Users\mmusa\Desktop\Dev\myApp\node_modules\@nodert-win10\windows.devices.geolocation
gyp ERR! node -v v10.8.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok
npm WARN myapp@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-redhat@0.5.0 (node_modules\electron-installer-redhat):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-redhat@0.5.0: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: electron-installer-debian@0.8.1 (node_modules\electron-installer-debian):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for electron-installer-debian@0.8.1: wanted {"os":"darwin,linux","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodert-win10/windows.devices.geolocation@0.2.96 install: `node-gyp rebuild --msvs_version=2015`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodert-win10/windows.devices.geolocation@0.2.96 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mmusa\AppData\Roaming\npm-cache\_logs\2018-08-10T15_49_56_869Z-debug.log
```
I've attached error screenshot too(As error was highlighted in red).
![2018-08-10_9-55-06](https://user-images.githubusercontent.com/36520/43968263-d1bc5896-9c83-11e8-8ed9-4de7f4ca4b8f.png)

Appreciate any help, Thanks.
Musa

**Comment by appskitchen** [comment]
I've resolved this myself. For those who are facing same issue as me I had Visual Studio 2017, but later I installed Visual Studio 2015 along with Windows 10 Development Kit. But that didn't solve the issue. Finally I copied Windows.winmd file
```
from 
C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17134.0\Windows.winmd
to
C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd
```

resolved the problem(Found the solution here - https://stackoverflow.com/a/42161291
