### ISSUE TITLE
"SyntaxError: invalid syntax" trying to add NodeRT to an Electron project

### ISSUE THREAD

**Issue by qmatteoq** [NodeRT/NodeRT#113]
Hello,
I'm trying to add NodeRT to the quick start project provided by Electron.
This is my environment:

- Windows 10 17763 (RS5)
- Visual Studio 2017 15.8
- Windows 10 SDK (16299, 17134 and 17764)
- Python 3.7
- Node v10.11.0

The problem is that, when I launch the following command:

`
npm install --save @nodert-win10-rs4/windows.ui.notifications
`

the process at some point breaks with the following error:

`
if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\mpagani\AppData\Local\Programs\Python\Python37\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:289:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\mpagani\Source\Samples\ElectronNotification\electron-quick-start\node_modules\@nodert-win10-rs4\windows.ui.notifications
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @nodert-win10-rs4/windows.ui.notifications@0.3.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @nodert-win10-rs4/windows.ui.notifications@0.3.2 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
`

What am I doing wrong? Am I missing any dependency?

Thanks!

**Comment by cruzerld** [comment]
Hey! I actually had the exact same issue and managed to fix it by installing the VS2015 build tools package that now comes with VS2017 as an optional package.

Install the package this way: https://blogs.msdn.microsoft.com/vcblog/2017/11/02/visual-studio-build-tools-now-include-the-vs2017-and-vs2015-msvc-toolsets/

If you use chocolatey I also have an install script to get you everything you need.

**Comment by jalbatross** [comment]
> I think I've found the issue. After setting up the environment in the right way, I've stumbled across another error related to the missing "platform.winmd" file. If I look at the binding.gyp file inside each downloaded project (for example, windows.ui.notifications), I can see the following lines:
> 
> `["WIN_VER==\"v10\"", { "msvs_settings": { "VCCLCompilerTool": { "AdditionalUsingDirectories": [ "%ProgramFiles(x86)%/Microsoft Visual Studio 14.0/VC/lib/store/references", "%ProgramFiles%/Microsoft Visual Studio 14.0/VC/lib/store/references" ] } } }]`
> 
> However, on my Windows 10 machine with the last version of Visual Studio, I don't have any of these folders. The "platform.winmd" file is stored inside C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\lib\x86\store\references.
> 
> As a workaround, manually copying the file inside another folder referenced by the binding file did the trick.

Matteo, thank you. Moving the platform.winmd file from

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.15.26726\lib\x86\store\references`

to

`C:\Program Files(x86\Windows Kits\10\UnionMetadata\10.0.17134.0`

 did the trick to fix the "platform.winmd" error for me!

**Comment by rajabilal555** [comment]
I believe a better solution to this would be to update binding.gyp accordingly for every system as I have 'Windows Kits' installed under `D:\Windows Kits\10`  and a way to do that would be to get the Windows Kit Install directory from `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\Microsoft\Microsoft SDKs\Windows\v10.0` and then `InstallationFolder`
that would be a much reliable source of installation directory

**Comment by RandomEngy** [comment]
I was able to resolve this issue by copying platform.winmd from

`C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\VC\vcpackages\x86`

to

`C:\Program Files (x86)\Windows Kits\10\UnionMetadata\10.0.17134.0`
