### ISSUE TITLE
Building on a machine that has VS2017 installed?

### ISSUE THREAD

**Issue by elliott-parkinson** [NodeRT/NodeRT#117]
I've been attempting to work with these libraries for a better part of a month on and off now - but never got them to install.

I've narrowed it down to having vs2017 installed. It would seem if it's installed on my PC the libraries simply cannot run. In MSVSVersion.py (line 424 and 434) it seems that there is a version map, that does not include 2017. Even though I have the 2015 build tools installed (as suggested in https://github.com/NodeRT/NodeRT/issues/113) I can never progress. It finds 2017 an then dies there (even with the 2015 build tools installed).

Below is my current error:
```> @nodert-win10-au/windows.devices.geolocation@0.2.96 install C:\Projects\Personal\nodert-test\node_modules\@nodert-win10-au\windows.devices.geolocation
> node-gyp rebuild --msvs_version=2015


C:\Projects\Personal\nodert-test\node_modules\@nodert-win10-au\windows.devices.geolocation>if not defined npm_config_node_gyp (node "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )  else (node "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild --msvs_version=2015 )
Traceback (most recent call last):
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\generator\msvs.py", line 1916, in CalculateVariables
    generator_flags.get('msvs_version', 'auto'))
  File "C:\Users\major\AppData\Local\nvs\node\10.9.0\x64\node_modules\npm\node_modules\node-gyp\gyp\pylib\gyp\MSVSVersion.py", line 434, in SelectVisualStudioVersion
    versions = _DetectVisualStudioVersions(version_map[version], 'e' in version)
KeyError: '2017'
```

Does anyone know of a workaround for this? I can't find a vs2015 installer anymore and I need 2017 as it is. It would be good to be able to use these libraries.

**Comment by ErraticFox** [comment]
The vs2015 installer is here, though I do agree. `@nodert-win10-cu/windows.media` does not seem to work unless I install VS 2015. Unless that means I'm _not_ installing something from VS 2017 manually (from within the component installer, I think it's called).
