### ISSUE TITLE
"Error: Not implemented" - when trying to pick contacts

### ISSUE THREAD

**Issue by ihappycoder** [NodeRT/NodeRT#126]
### System

Windows 10, 1809
SDK: 1709

### Module

`@nodert-win10-rs3/windows.applicationmodel.contacts`

### Code to reproduce

```javascript
const contacts = require('@nodert-win10-rs3/windows.applicationmodel.contacts')
const contactsPicker = new contacts.ContactPicker();

contactsPicker.selectionMode = contacts.ContactSelectionMode.fields
contactsPicker.desiredFieldsWithContactFieldType.append(contacts.ContactFieldType.email)

contactsPicker.pickContactAsync(
    (error, success) => console.log(error, success)
)
```

### Output

```
contactsPicker.pickContactAsync(
               ^

Error: Not implemented

Not implemented

    at Object.<anonymous> (C:\Users\IPU\Test\test.js:7:16)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by felixrieseberg** [comment]
I don't think you can launch a contact picker outside of UWP apps because they need a Core Window. Either way, that error is coming straight from Windows, I'm afraid.

**Comment by ihappycoder** [comment]
@felixrieseberg thanks for your answer, then maybe you know how I can just fetch windows contacts using NodeRT (or any other electron compatible solution, I just need functionality similar to [node-addressbook](https://github.com/wireapp/node-addressbook/) on mac os)? Thanks!
