### ISSUE TITLE
Cannot build module with specific NODE_MODULE_VERSION 72

### ISSUE THREAD

**Issue by smilovich** [NodeRT/NodeRT#128]
I tried to build NodeRT module with node-gyp
`node-gyp configure --target=v10.16.0 --msvs_version=2017`
checked that .\build\config.gypi have line
`"node_module_version": 72`
than 
`node-gyp build`
everything builds fine, but when I try to load the result module in node terminal, I'm getting following error:
```
> const a3 = require('./binding')
Thrown:
Error: The module '\\?\C:\Electron\NodeRT-3.0.0\src\NodeRTUI\bin\Debug\output\windows.devices.geolocation\build\Release\binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:817:18)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
```
I also tried to rebuild this project with VS2019 and have same issue after that.
And I tried to build from sources 
`node-gyp rebuild --target=v10.16.0 --arch=x64 --dist-url=https://atom.io/download/electron --build-from-source --msvs_version=2017`
and also no luck. 
Can anybody help me to build NodeRT module with correct NODE_MODULE_VERSION version?

**Comment by daibatzu** [comment]
I have the same problem. Please help anybody

**Comment by dtbenson43** [comment]
This is actually a problem with electron using different versions of node than the version of node the package was compild with. You need to use [electron-rebuild](https://www.npmjs.com/package/electron-rebuild) to rebuild native packages for electron. Or if you don't want to use that package, you can use `process.versions` inside electron to get the correct node version and then reinstall the packages.

**Comment by daibatzu** [comment]
Thanks. I built an exe instead to resolve this. https://github.com/daibatzu/electron-sharing
