### ISSUE TITLE
fatal error C1128: number of sections exceeded object file format limit : compile with /bigobj

### ISSUE THREAD

**Issue by yangarnet** [NodeRT/NodeRT#143]
Windows 10
electron: 8.2.0
SDK: windows 10.0.17134.12

when try to run : **$yarn add @nodert-win10-rs4/windows.storage**
the following error ocurrs:
fatal error C1128: number of sections exceeded object file format limit: compile with /bigobj [D:\myproject-wpd\@nodert-win10-rs4\windows.storage\build\binding.vcxproj]
cl : Command line error D8040: error creating or communicating with child process
[D:\myproject-wpd\@nodert-win10-rs4\windows.storage\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxxxxxxxx\AppData\Roaming\nvm\v12.14.1\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.19041
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\myproject-wpd\@nodert-win10-rs4\windows.storage
gyp ERR! node -v v12.14.1

proposed solution to make changes to the  binding.gyp in the project, adding extra field as the following 👍 
`
"msvs_settings": {
      "VCCLCompilerTool": {
        "AdditionalOptions": ["/ZW", "/bigobj"],
        "DisableSpecificWarnings": [4609]
      }
    }
`

Cannot make a PR to this repo. so put it here
can anyone who make the change?  

thanks

**Comment by markibanez** [comment]
I couldn't wait for these changes to come through. For those who need this right now you can build it yourself with the steps below.

From the module creation guide https://github.com/NodeRT/NodeRT/blob/master/MODULE_CREATION.md

1. Install Visual Studio 2017 (I installed C++ and UWP)

2. Clone NodeRT repo to your local system with this command `git clone https://github.com/NodeRT/NodeRT.git`

3. Inside the cloned repo, open `/src/NodeRT.sln` with Visual Studio 2017

4. Build and run the NodeRTUI Project (You may need to set it as the startup project). That should open the NodeRT Modules Generator app.

![image](https://user-images.githubusercontent.com/7534847/88449843-e6b35380-ce7c-11ea-8366-bbd87a892163.png)

5. Choose a WinMD file. On Windows 10 that would be `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'. Please check the guide above for Windows 8.1 and 8

6. Filter for windows.storage by typing it on the filter box

![image](https://user-images.githubusercontent.com/7534847/88449865-14000180-ce7d-11ea-83eb-65966c314ba8.png)

7. Click on "Generate and build module" button at the bottom of the window. It will notify you when it is done.

8. Update binding.gyp file as stated by @yangarnet above. It is located in `<module-output-directory>/windows.storage`. 

Line 70-75 should look like this
```
    "msvs_settings": {
      "VCCLCompilerTool": {
        "AdditionalOptions": ["/ZW"],
        "DisableSpecificWarnings": [4609]
      }
    }
```
Change line 72 from `"AdditionalOptions": ["/ZW"]` to `"AdditionalOptions": ["/ZW", "/bigobj"]`

9. From there you can run `npm install <module-output-directory>/windows.storage` to add and install it to your project

**Comment by yangarnet** [comment]
> I couldn't wait for these changes to come through. For those who need this right now you can build it yourself with the steps below.
> 
> From the module creation guide https://github.com/NodeRT/NodeRT/blob/master/MODULE_CREATION.md
> 
> 1. Install Visual Studio 2017 (I installed C++ and UWP)
> 2. Clone NodeRT repo to your local system with this command `git clone https://github.com/NodeRT/NodeRT.git`
> 3. Inside the cloned repo, open `/src/NodeRT.sln` with Visual Studio 2017
> 4. Build and run the NodeRTUI Project (You may need to set it as the startup project). That should open the NodeRT Modules Generator app.
> 
> ![image](https://user-images.githubusercontent.com/7534847/88449843-e6b35380-ce7c-11ea-8366-bbd87a892163.png)
> 
> 1. Choose a WinMD file. On Windows 10 that would be `C:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd'. Please check the guide above for Windows 8.1 and 8
> 2. Filter for windows.storage by typing it on the filter box
> 
> ![image](https://user-images.githubusercontent.com/7534847/88449865-14000180-ce7d-11ea-83eb-65966c314ba8.png)
> 
> 1. Click on "Generate and build module" button at the bottom of the window. It will notify you when it is done.
> 2. Update binding.gyp file as stated by @yangarnet above. It is located in `<module-output-directory>/windows.storage`.
> 
> Line 70-75 should look like this
> 
> ```
>     "msvs_settings": {
>       "VCCLCompilerTool": {
>         "AdditionalOptions": ["/ZW"],
>         "DisableSpecificWarnings": [4609]
>       }
>     }
> ```
> 
> Change line 72 from `"AdditionalOptions": ["/ZW"]` to `"AdditionalOptions": ["/ZW", "/bigobj"]`
> 
> 1. From there you can run `npm install <module-output-directory>/windows.storage` to add and install it to your project

Thank you sir,
yes I tried the above workaround to fix the problem, cannot wait the fix anymore :)

**Comment by kennyhyun** [comment]
I could add bigobj without installing VS

- Init a npm package and install `windows.storage` anywhere in your PC
```
$ npm init -y
$ npm install @nodert-win10-rs4/windows.storage --ignore-scripts
```
- and move the package from the node_modules to somewhere in your project
```
$ mv node_modules/@nodert-win10-rs4/windows.storage ../SOMEWHERE_IN_YOU_PROJECT
```
- and then add `/bigobj` into binding.gyp

```
"msvs_settings": {
    "VCCLCompilerTool": {
-            "AdditionalOptions": ["/ZW"],
+            "AdditionalOptions": ["/ZW", "/bigobj"],
	     "DisableSpecificWarnings": [4609]
    }
 }
```
- Now you can add @nodert-win10-rs4/windows.storage using `file:` for example,
```
    "@nodert-win10-rs4/windows.storage": "file:../SOMEWHERE_IN_YOU_PROJECT/windows.storage",
```

**Comment by marchbold** [comment]
Just had success with a slight modification of @kennyhyun's solution. you can directly install it into your project 

```sh
npm i --save @nodert-win10-rs4/windows.storage --ignore-scripts
```

Edit the `binding.gyp` adding the `"/bigobj"` option as above, then rebuild with:

```sh
npm rebuild @nodert-win10-rs4/windows.storage
```
