### ISSUE TITLE
Unable to install @nodert-win10/windows.applicationmodel.contacts package

### ISSUE THREAD

**Issue by raineesh-liri** [NodeRT/NodeRT#161]
I could not install the package @nodert-win10/windows.applicationmodel.contacts into electron app/react js app.
I followed the steps mentioned in https://www.npmjs.com/package/@nodert-win10/windows.applicationmodel.contacts 
And I tried with different versions of Visual Studio 2015, 2017 & 2019. But it failed. 

Getting this error

npm ERR!   C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\functional(472): note: see declaration of 'std::function'
npm ERR! d:\web projects\contacts-v1\node_modules\@nodert-win10\windows.applicationmodel.contacts\node-async.h(254): fatal error C1903: unable to recover from previous error(s); stopping compilation [D:\Web Projects\contacts-v1\node_modules\@nodert-win10\windows.applicationmodel.contacts\build\binding.vcxproj]
npm ERR!   Internal Compiler Error in C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe.  You will be prompted to send an error report to Microsoft later.
npm ERR!   INTERNAL COMPILER ERROR in 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin\amd64\CL.exe'
npm ERR!       Please choose the Technical Support command on the Visual C++
npm ERR!       Help menu, or open the Technical Support help file for more information
npm ERR! gyp info it worked if it ends with ok
npm ERR! gyp info using node-gyp@8.4.1
npm ERR! gyp info using node@14.16.1 | win32 | x64
npm ERR! gyp info find Python using Python version 3.9.0 found at "C:\Users\LIRISOFT\scoop\apps\python\current\python.exe"
npm ERR! gyp info find VS using VS2015 (14.0) found at:
npm ERR! gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio 14.0"
npm ERR! gyp info find VS run with --verbose for detailed information
npm ERR! gyp info spawn C:\Users\LIRISOFT\scoop\apps\python\current\python.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'C:\\Users\\LIRISOFT\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
npm ERR! gyp info spawn args   'binding.gyp',
npm ERR! gyp info spawn args   '-f',
npm ERR! gyp info spawn args   'msvs',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Web Projects\\contacts-v1\\node_modules\\@nodert-win10\\windows.applicationmodel.contacts\\build\\config.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'D:\\Web Projects\\contacts-v1\\node_modules\\@nodert-win10\\windows.applicationmodel.contacts\\common.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\LIRISOFT\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',
npm ERR! gyp info spawn args   '-I',
npm ERR! gyp info spawn args   'C:\\Users\\LIRISOFT\\AppData\\Local\\node-gyp\\Cache\\14.16.1\\include\\node\\common.gypi',
npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
npm ERR! gyp info spawn args   '-Dvisibility=default',
npm ERR! gyp info spawn args   '-Dnode_root_dir=C:\\Users\\LIRISOFT\\AppData\\Local\\node-gyp\\Cache\\14.16.1',
npm ERR! gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\LIRISOFT\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp',
npm ERR! gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\LIRISOFT\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\14.16.1\\\\<(target_arch)\\\\node.lib',
npm ERR! gyp info spawn args   '-Dmodule_root_dir=D:\\Web Projects\\contacts-v1\\node_modules\\@nodert-win10\\windows.applicationmodel.contacts',
npm ERR! gyp info spawn args   '-Dnode_engine=v8',
npm ERR! gyp info spawn args   '--depth=.',
npm ERR! gyp info spawn args   '--no-parallel',
npm ERR! gyp info spawn args   '--generator-output',
npm ERR! gyp info spawn args   'D:\\Web Projects\\contacts-v1\\node_modules\\@nodert-win10\\windows.applicationmodel.contacts\\build',
npm ERR! gyp info spawn args   '-Goutput_dir=.'
npm ERR! gyp info spawn args ]
npm ERR! gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe
npm ERR! gyp info spawn args [
npm ERR! gyp info spawn args   'build/binding.sln',
npm ERR! gyp info spawn args   '/clp:Verbosity=minimal',
npm ERR! gyp info spawn args   '/nologo',
npm ERR! gyp info spawn args   '/p:Configuration=Release;Platform=x64'
npm ERR! gyp info spawn args ]
npm ERR! gyp ERR! build error
npm ERR! gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\MSBuild.exe` failed with exit code: 1
npm ERR! gyp ERR! stack     at ChildProcess.onExit (C:\Users\LIRISOFT\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23)
npm ERR! gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
npm ERR! gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
npm ERR! gyp ERR! System Windows_NT 10.0.19043
npm ERR! gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\LIRISOFT\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
npm ERR! gyp ERR! cwd D:\Web Projects\contacts-v1\node_modules\@nodert-win10\windows.applicationmodel.contacts
npm ERR! gyp ERR! node -v v14.16.1
npm ERR! gyp ERR! node-gyp -v v8.4.1
npm ERR! gyp ERR! not ok

**Comment by bsdlp** [comment]
it looks like there's a few other threads about this but i haven't found a working solution - were you able to resolve this?
