### ISSUE TITLE
Fails to build Windows.Graphics.Holographic

### ISSUE THREAD

**Issue by doublerebel** [NodeRT/NodeRT#45]
I see **@nodert-win10/windows.graphics.directx.direct3d11** is published, so I thought I would give Windows.Graphics.Holographic a shot.

Fails with:
```sh
C:\Users\charles\Source\NodeRT>NodeRTCmd.exe --verbose --winmd "c:\Program Files (x86)\Windows Kits\10\UnionMetadata\Windows.winmd" --codegendir c:\Users\charles\Source\NodeRT\codegen --outdir c:\Users\charles\Source\NodeRT\output --namespace Windows.Graphics.Holographic
Generating code for: Windows.Graphics.Holographic...
Building Windows.Graphics.Holographic...
gyp info it worked if it ends with ok
gyp info using node-gyp@3.4.0
gyp info using node@6.7.0 | win32 | x64
gyp http GET https://nodejs.org/download/release/v6.7.0/node-v6.7.0-headers.tar.gz
gyp http 200 https://nodejs.org/download/release/v6.7.0/node-v6.7.0-headers.tar.gz
gyp http GET https://nodejs.org/download/release/v6.7.0/SHASUMS256.txt
gyp http GET https://nodejs.org/download/release/v6.7.0/win-x86/node.lib
gyp http GET https://nodejs.org/download/release/v6.7.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v6.7.0/SHASUMS256.txt
gyp http 200 https://nodejs.org/download/release/v6.7.0/win-x64/node.lib
gyp http 200 https://nodejs.org/download/release/v6.7.0/win-x86/node.lib
gyp info spawn C:\Python27\python.exe
gyp info spawn args [ 'C:\\Users\\charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-G',
gyp info spawn args   'msvs_version=2015',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Users\\charles\\Source\\NodeRT\\output\\windows.graphics.holographic\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'c:\\Users\\charles\\Source\\NodeRT\\output\\windows.graphics.holographic\\common.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\charles\\.node-gyp\\6.7.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\charles\\.node-gyp\\6.7.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=node.lib',
gyp info spawn args   '-Dmodule_root_dir=c:\\Users\\charles\\Source\\NodeRT\\output\\windows.graphics.holographic',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'c:\\Users\\charles\\Source\\NodeRT\\output\\windows.graphics.holographic\\build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe
gyp info spawn args [ 'build/binding.sln',
gyp info spawn args   '/clp:Verbosity=minimal',
gyp info spawn args   '/nologo',
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  _nodert_generated.cpp
  NodeRtUtils.cpp
  OpaqueWrapper.cpp
  CollectionsConverterUtils.cpp
  win_delay_load_hook.cc
c:\users\charles\source\nodert\output\windows.graphics.holographic\node-async.h(235): warning C4311: 'type cast': pointer truncation from 'uv_thread_t' to 'unsigned int' (compiling source file ..\_nodert_generated.cpp) [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
c:\users\charles\source\nodert\output\windows.graphics.holographic\node-async.h(235): warning C4302: 'type cast': truncation from 'uv_thread_t' to 'unsigned int' (compiling source file ..\_nodert_generated.cpp) [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(127): error C3861: 'IsMatrix4x4JsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(136): error C3861: 'IsMatrix4x4JsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(162): error C3861: 'Matrix4x4FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(168): error C3861: 'Matrix4x4FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(180): error C3861: 'Matrix4x4ToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(181): error C3861: 'Matrix4x4ToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(355): error C3861: 'IsPlaneJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(364): error C3861: 'IsPlaneJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(373): error C3861: 'IsPlaneJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(382): error C3861: 'IsPlaneJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(391): error C3861: 'IsPlaneJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(400): error C3861: 'IsPlaneJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(426): error C3861: 'PlaneFromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(432): error C3861: 'PlaneFromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(438): error C3861: 'PlaneFromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(444): error C3861: 'PlaneFromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(450): error C3861: 'PlaneFromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(456): error C3861: 'PlaneFromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(468): error C3861: 'PlaneToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(469): error C3861: 'PlaneToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(470): error C3861: 'PlaneToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(471): error C3861: 'PlaneToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(472): error C3861: 'PlaneToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(473): error C3861: 'PlaneToJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(519): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(519): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(519): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(519): error C2146: syntax error: missing ';' before identifier 'Vector3FromJsObject' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(520): error C2143: syntax error: missing ';' before '{' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(520): error C2447: '{': missing function header (old-style formal list?) [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(554): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(554): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(554): error C2146: syntax error: missing ')' before identifier 'value' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(555): error C2143: syntax error: missing ';' before '{' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(555): error C2447: '{': missing function header (old-style formal list?) [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2854): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2854): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(2854): error C2146: syntax error: missing ';' before identifier 'arg1' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2854): error C2065: 'arg1': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2854): error C3861: 'Vector3FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2856): error C2065: 'arg1': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2873): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2873): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(2873): error C2146: syntax error: missing ';' before identifier 'arg1' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2873): error C2065: 'arg1': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2873): error C3861: 'Vector3FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2874): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2874): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(2874): error C2146: syntax error: missing ';' before identifier 'arg2' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2874): error C2065: 'arg2': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2874): error C3861: 'Vector3FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2876): error C2065: 'arg1': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2876): error C2065: 'arg2': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2894): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2894): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(2894): error C2146: syntax error: missing ';' before identifier 'arg1' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2894): error C2065: 'arg1': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2894): error C3861: 'Vector3FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2895): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2895): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(2895): error C2146: syntax error: missing ';' before identifier 'arg2' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2895): error C2065: 'arg2': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2895): error C3861: 'Vector3FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2896): error C3083: 'Numerics': the symbol to the left of a '::' must be a type [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2896): error C2039: 'Vector3': is not a member of 'Platform' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\collection.h(2165): note: see declaration of 'Platform'
..\_nodert_generated.cpp(2896): error C2146: syntax error: missing ';' before identifier 'arg3' [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2896): error C2065: 'arg3': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2896): error C3861: 'Vector3FromJsObject': identifier not found [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2898): error C2065: 'arg1': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2898): error C2065: 'arg2': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
..\_nodert_generated.cpp(2898): error C2065: 'arg3': undeclared identifier [c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic\build\binding.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\charles\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\charles\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--msvs_version=2015"
gyp ERR! cwd c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok


Failed to build the generated project, please try to build the project manually
Generated project files are located at: c:\Users\charles\Source\NodeRT\output\windows.graphics.holographic
```

I have some experience building native NodeJS extensions for Linux and Solaris, where's a good place to start fixing this one?

Sidenote: Python 2.7.x should probably be mentioned as a dependency for node-gyp.  I didn't realize it was missing until I built from the CLI with `--verbose`.

**Comment by nadavbar** [comment]
This is basically same as this issue: https://github.com/NodeRT/NodeRT/issues/18
For some reason it seems like the problematic structs are defined in another .winmd file (UniversalAPiContract.winmd). However, if you try to add this file to the list of winmd file that the project is consuming, you get a bunch of other errors regarding collisions. 
What basically need to be done is to find the right combinations of winmd files that will cause this to compile. It might be a chance that we need to use another winmd file in order to generate this specific namespace, I haven't had a chance to test it yet.

I didn't have the time to look into this yet, but let me know if you want to take this forward and I'll be happy to provide guidance.

One thing that you should take in mind though is that the classes of this namespace does not have the [DualApiPartition](https://msdn.microsoft.com/en-gb/library/windows/apps/windows.foundation.metadata.dualapipartitionattribute.aspx) flag, so you'll probably be only able to use it as part of a windows store app, via the electron - windows store bridge. (Some things like specific utility classes might work from desktop though..)

Regarding: python dependency for node-gyp, it's a general issue with all node native module AFAIK. I've added issue #46 for tracking adding this to the doc.

**Comment by doublerebel** [comment]
Interesting, thanks for the details.  I would like to take this forward, and should have some time next week to look at it in more depth.

I don't have any plans to use Electron, I just want to be able to create DirectX calls from JavaScript on the device.  I'm creating business-focused apps on Hololens (in C++, not gaming, no Unity) and it would be ideal to be able to reuse the JS ecosystem for business logic, and eventually maybe even port some WebGL.

Are .winmd files always needed in their entirety or is it possible to remove offending sections?  i.e. could the necessary packages be generated with a little manual editing?

**Comment by nadavbar** [comment]
AFAIK The VS C++ compiler always imports the entire WinMD files, hence the problem with the duplicate definitions. My guess here that we might use another WinMD file from the Windows 10 SDK that might not be windows.winmd, but I didn't had the chance to verify this.

Does not using Electron imply that you actually have node.js running on the the device? Or are you running it remotely?

**Comment by doublerebel** [comment]
ChakraCore runs on the device, one such attempt is [HolographicJS](https://github.com/lwansbrough/HolographicJS) which uses ANGLE.  I'd rather use the DirectX calls than ANGLE if possible.  I have some familiarity with these hybrid systems, I've developed several apps and modules with Appcelerator Titanium.  I'm thinking something more like (or even a port of) React Native or Exponent, in 3D.

**Comment by nadavbar** [comment]
Got it. BTW, did you try to run node-chakra (not chakracore), it uses the native Chakra library that comes with windows and can expose the UWP APIs using the <a href="https://github.com/Microsoft/node-uwp">node-uwp</a> module. The module uses  a method that is specific to Chakra in order to expose UWP APIs to JS and hence only works with node-chakra.
