### ISSUE TITLE
Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by quanglam2807** [NodeRT/NodeRT#58]
Hi, I used NodeRT in my Electron app on Windows 10 + Visual Studio 2017 but I received this error. Please help!

```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\quanglam2807\Projects\webcatalog\app\node_modules\@nodert-win10\windows.ui.notifications\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\quanglam2807\Projects\webcatalog\app\node_modules\@nodert-win10\windows.ui.notifications\lib\main.js:19:20)
    at Object.<anonymous> (C:\Users\quanglam2807\Projects\webcatalog\app\node_modules\@nodert-win10\windows.ui.notifications\lib\main.js:64:3)
```

**Comment by nadavbar** [comment]
Did you use VS 2017 to compile? We haven't tested it yet with VS 2017..
I'll try to look into that, but If possible I would try to compile with VS 2015 in the meantime

**Comment by quanglam2807** [comment]
@nadavbar Please apologize for my late response. Yes, I used VS 2017 to compile. As you mentioned, I will try to use VS 2015 instead but I hope you would add support for VS 2017 soon. I think this: https://github.com/nodejs/node-gyp/issues/1056 will be useful for you.

**Comment by dpalou** [comment]
I have the same problem. I've installed VS 2015 and uninstalled VS 2017 just in case.

I get the error when using the library "electron-windows-notifications". The library installs fine, but when I require it in the JS code I get the same error but with the library "@nodert-win10\windows.data.xml.dom":

```
Uncaught Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\...\node_modules\@nodert-win10\windows.data.xml.dom\build\Release\binding.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\...\node_modules\@nodert-win10\windows.data.xml.dom\lib\main.js:19:20)
    at Object.<anonymous> (C:\Users\...\node_modules\@nodert-win10\windows.data.xml.dom\lib\main.js:64:3)
```

FYI I also had this problem: https://github.com/NodeRT/NodeRT/issues/65. I solved it by copying the file from UnionMetadata\10.0.15063.0 as d-rep suggested.

Any suggestion? Were you able to solve it, @quanglam2807?

**Comment by quanglam2807** [comment]
@dpalou Not at all. :(

**Comment by dpalou** [comment]
I was finally able to fix it, but I had to use electron-rebuild. Using a .npmrc file when installing the modules didn't work, I had to rebuilding them all after being installed.

**Comment by obermillerk** [comment]
@dpalou I'm still having this issue after trying to use electron rebuild.  What flags are you using to rebuild?

**Comment by dpalou** [comment]
I ran it like this:

.\node_modules\.bin\electron-rebuild -v 1.6.1

When running electron-builder it says it's rebuilding dependencies or something like this, so I guess it runs electron-rebuild too.

**Comment by obermillerk** [comment]
I got it working using `node-gyp rebuild --target=1.6.11 --arch=x64 --dist
-url=https://atom.io/download/atom-shell`.  For some reason electron rebuild didn't work for me but this did.
