### ISSUE TITLE
Setting object's Guid property

### ISSUE THREAD

**Issue by logidelic** [NodeRT/NodeRT#67]
How can one set an object's Guid property? I tried the following:

```
var PdfPageRenderOptions = require('@nodert-win10/windows.data.pdf').PdfPageRenderOptions;
var BitmapEncoder        = require('@nodert-win10/windows.graphics.imaging').BitmapEncoder;

var opts = new PdfPageRenderOptions();
opts.bitmapEncoderId = BitmapEncoder.bmpEncoderId;
```

Both `BitmapEncoder.bmpEncoderId` and `opts.bitmapEncoderId` should be of type `Guid`, but I get the following exception:

```
Uncaught Error: Value to set is of unexpected type
Error: Value to set is of unexpected type
    at EventEmitter.<anonymous> (C:\Users\logi\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:372:15)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\logi\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at EventEmitter.<anonymous> (C:\Users\logi\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:372:15)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\logi\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\logi\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:234:13)
    at Object.descriptor.set [as bitmapEncoderId] (C:\Users\logi\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:147:13)
    at eval (eval at evaluate (:85:21), <anonymous>:1:24)
```

I tried to find the Guid class somewhere in the NodeRT namespaces (ex windows.system) but it doesn't seem to be there...

**Comment by nadavbar** [comment]
NodeRT does implicit conversions of Guid to (and from) strings (similarly to UWP JavaScript). So you should be able to set this property using a string of a guid.
Can you try and print BitmapEncoder.bmpEncoderId and see what you get?

**Comment by logidelic** [comment]
Inspecting before I attempt to set:

`opts.bitmapEncoderId`: "{27949969-876A-41D7-9447-568F6A35A4DC}"

`BitmapEncoder.bmpEncoderId`: "{69BE8BB4-D66D-47C8-865A-ED1589433782}"

**Comment by nadavbar** [comment]
OK, I found the problem. For some reason the GUID validation code expects to receive a string without the curly brackets as the guid.
Until we'll fix this issue, you can use the following workaround:
```
var PdfPageRenderOptions = require('./windows.data.pdf').PdfPageRenderOptions;
var BitmapEncoder        = require('./windows.graphics.imaging').BitmapEncoder;

var opts = new PdfPageRenderOptions();
encoderGuid = BitmapEncoder.bmpEncoderId
opts.bitmapEncoderId = encoderGuid.substr(1,encoderGuid.length-2);
```

**Comment by logidelic** [comment]
Works, thank you! I'll let you close the issue when the underlying bug is fixed. :)
